marketCode: Binance
symbolType: Spot

saveMarketData: true

addrOfSymbolTable: "https://data.binance.com/api/v3/exchangeInfo"
addrOfWSPub: "wss://data-stream.binance.com:9443/ws"

enableSymbolTableMaint: true

wsParam: svcName=WSCli; milliSecIntervalOfSendPingAndCheckConn=5000; sendPing=1; expireTimeOfConn=120000
wsTaskDispatcherParam: moduleName=wsCliTaskDispatcher; taskRandAssignedThreadPoolSize=0; taskSpecificThreadPoolSize=2

milliSecIntervalOfSymbolTableMaint: 60000
timeoutOfQuerySymbolTableFromExch: 60000

dbEngParam: svcName=dbEng; dbName=BetterQuant; host=0.0.0.0; port=3306; username=root; password=showmethemoney
dbTaskDispatcherParam: moduleName=dbTaskDispatcher

milliSecIntervalOfTBLMonitorOfSymbolInfo: 10000
milliSecIntervalOfTopicGroupMustSubMaint: 1000

topicGroupMustSubInAdvance: config/bqmd-binance/spot/TopicGroupMustSubInAdvance.yaml
topicGroupInBlackList: config/bqmd-binance/spot/TopicGroupInBlackList.yaml
thresholdOfReSubWithoutRecvMD: config/bqmd-binance/spot/ThresholdOfReSub.yaml

addrOfSnapshot: https://data.binance.com/api/v3/depth?symbol=symbolCode&limit=1000
timeoutOfQuerySnapshot: 60000

defaultExchMDTypeBooks: depth@100ms
defaultBooksDepthGroup: [5, 20, 200, 400]
booksDepthLevelOfSave: 20

subAndUnSubSvcParam: moduleName=subAndUnSubSvcOfBinance; taskRandAssignedThreadPoolSize=0; taskSpecificThreadPoolSize=1
mdStorageSvcParam: moduleName=mdStorageSvcOfBinance; numOfUnprocessedTaskAlert=1000; taskSpecificThreadPoolSize=0

storageRootPath: data
thresholdOfMDRowNumInCache: 100
maxNumOfHisMDCanBeQeuryEachTime: 10000

flowCtrlRule:
  - taskGroup:
    - {name: Sub, weight: 1}
    - {name: UnSub, weight: 1}
    timeDur: 500
    limitNum: 1

logger: 
  queueSize: 128
  backingThreadsCount: 1
  defaultLoggerName: defaultLogger
  loggerGroup: 
    - 
      loggerName: "defaultLogger"
      maxFiles: 10
      maxSize: 104857600
      outputDir: "data/logs/bqmd/bqmd-binance-spot"
      outputFilename: "bqmd-binance-spot"
      rotatingSinkPattern: "[%Y%m%d %T.%f] [%L] [%t] [%s:%#] %v"
      stdoutSinkPattern: "[%Y%m%d %T.%f] [%^%L%$] [%t] [%s:%#] %v"
